package main

func main() {
	bTree := newBTree(5)
	bTree.insertElem("a", []byte("monke"), true)
	bTree.insertElem("b", []byte("monke"))
	bTree.insertElem("c", []byte("monke"))
	bTree.insertElem("d", []byte("monke"))
	bTree.insertElem("e", []byte("monke"))
	bTree.insertElem("f", []byte("monke"))
	bTree.insertElem("p", []byte("monke"))
	bTree.insertElem("m", []byte("monke"))
	bTree.insertElem("q", []byte("monk"))
	bTree.insertElem("o", []byte("monke"))
	bTree.insertElem("s", []byte("monke"))
	bTree.insertElem("k", []byte("monke"))
	bTree.insertElem("j", []byte("monk"))
	bTree.insertElem("t", []byte("monke"))
	bTree.insertElem("g", []byte("monk"))
	bTree.insertElem("r", []byte("monke"))
	bTree.insertElem("l", []byte("monke"))
	bTree.insertElem("x", []byte("monke"))
	bTree.insertElem("u", []byte("monk"))
	bTree.insertElem("h", []byte("monke"))
	bTree.insertElem("v", []byte("monke"))
	bTree.insertElem("n", []byte("monke"))
	bTree.insertElem("z", []byte("monke"))
	bTree.remove("g")
	bTree.printBTree()
}
